// KAMSA regional chapter data. Source: KAMSA Regional Leadership workbook.
// `roster` = submitted leadership rows (no email addresses published).
// `contacts` = chapter contacts on file where no roster has been submitted yet.
// `schoolsPartial: true` = list not yet confirmed by the chapter.

export const NATIONAL = {
  email: "kamsa.usa@gmail.com",
  instagram: "https://www.instagram.com/kamsa.usa/",
  instagramHandle: "@kamsa.usa",
  discord: "https://discord.gg/EyeU2wSkG",
  form: "https://forms.gle/wnx6NDXZj9i2xNzL9",
  microGrant: "https://forms.gle/iBjudWBSMmw7KeeB6",
  newChapter: "https://forms.gle/PB26E5aSj8Nr8Rbq7",
  youtube: "https://www.youtube.com/@kamsausa",
};

export const CHAPTERS = [
  {
    slug: "ny-nj",
    name: "New York / New Jersey",
    short: "NY/NJ",
    lat: 40.7128, lon: -74.006,
    label: { dx: 210, dy: -70, align: "left" },
    email: "kamsanynj@gmail.com",
    instagram: "@kamsanynj",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://icahn.mssm.edu", name: "Icahn School of Medicine at Mount Sinai", city: "New York, NY" },
      { url: "https://www.hmsom.org", name: "Hackensack Meridian School of Medicine", city: "Nutley, NJ" },
      { url: "https://www.vagelos.columbia.edu", name: "Columbia University Vagelos College of Physicians and Surgeons", city: "New York, NY" },
      { url: "https://med.nyu.edu", name: "NYU Grossman School of Medicine", city: "New York, NY" },
      { url: "https://www.einsteinmed.edu", name: "Albert Einstein College of Medicine", city: "Bronx, NY" },
      { url: "https://renaissance.stonybrookmedicine.edu", name: "Renaissance School of Medicine at Stony Brook University", city: "Stony Brook, NY" },
      { url: "https://rwjms.rutgers.edu", name: "Rutgers Robert Wood Johnson Medical School", city: "New Brunswick, NJ" },
    ],
    roster: [],
    contacts: [
      { name: "Minwoo Kwon", role: "Chapter contact", school: "Icahn School of Medicine at Mount Sinai" },
      { name: "Sohee Kim", role: "Chapter contact", school: "Hackensack Meridian School of Medicine" },
    ],
  },
  {
    slug: "new-england",
    name: "New England",
    short: "New England",
    lat: 42.3601, lon: -71.0589,
    label: { dx: 210, dy: -120, align: "left" },
    email: "kamsanewengland@gmail.com",
    instagram: "@kamsa.ne",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://www.umassmed.edu", name: "UMass Chan Medical School", city: "Worcester, MA" },
      { url: "https://geiselmed.dartmouth.edu", name: "Dartmouth Geisel School of Medicine", city: "Hanover, NH" },
      { url: "https://www.une.edu/com", name: "University of New England College of Osteopathic Medicine", city: "Biddeford, ME" },
      { url: "https://hms.harvard.edu", name: "Harvard Medical School", city: "Boston, MA" },
      { url: "https://www.bumc.bu.edu/busm/", name: "Boston University Chobanian & Avedisian School of Medicine", city: "Boston, MA" },
      { url: "https://medicine.tufts.edu", name: "Tufts University School of Medicine", city: "Boston, MA" },
      { url: "https://medicine.yale.edu", name: "Yale School of Medicine", city: "New Haven, CT" },
      { url: "https://www.brown.edu/academics/medical/", name: "Warren Alpert Medical School of Brown University", city: "Providence, RI" },
    ],
    roster: [
      { name: "Sarah (So Jung) Park", role: "President", school: "UMass Chan Medical School" },
      { name: "Grace Jung", role: "Vice President", school: "UMass Chan Medical School" },
      { name: "SungJin Shin", role: "Secretary", school: "University of New England College of Osteopathic Medicine" },
      { name: "Seohyun (Cece) Hong", role: "Communications Chair", school: "UMass Chan Medical School" },
      { name: "Eric Lee", role: "Communications Chair", school: "UMass Chan Medical School" },
      { name: "Meghan Lauze", role: "Outreach Chair", school: "UMass Chan Medical School" },
      { name: "Sue Lee", role: "Advocacy Chair", school: "Dartmouth Geisel School of Medicine" },
    ],
    contacts: [],
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    short: "Pennsylvania",
    lat: 39.9526, lon: -75.1652,
    label: { dx: 210, dy: -20, align: "left" },
    email: "kamsa.penn@gmail.com",
    instagram: "@kamsa_penn",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://www.pcom.edu", name: "Philadelphia College of Osteopathic Medicine", city: "Philadelphia, PA" },
      { url: "https://www.med.upenn.edu", name: "University of Pennsylvania Perelman School of Medicine", city: "Philadelphia, PA" },
      { url: "https://drexel.edu/medicine/", name: "Drexel University College of Medicine", city: "Philadelphia, PA" },
      { url: "https://medicine.temple.edu", name: "Lewis Katz School of Medicine at Temple University", city: "Philadelphia, PA" },
      { url: "https://www.medschool.pitt.edu", name: "University of Pittsburgh School of Medicine", city: "Pittsburgh, PA" },
      { url: "https://med.psu.edu", name: "Penn State College of Medicine", city: "Hershey, PA" },
      { url: "https://www.jefferson.edu/academics/colleges-schools-institutes/skmc.html", name: "Sidney Kimmel Medical College at Thomas Jefferson University", city: "Philadelphia, PA" },
    ],
    roster: [
      { name: "Jina Park", role: "President", school: "Philadelphia College of Osteopathic Medicine" },
      { name: "C. James Kim", role: "President", school: "University of Pittsburgh School of Medicine" },
      { name: "Ashley Kim", role: "Vice President", school: "Penn State College of Medicine" },
      { name: "Kenneth Um", role: "Vice President", school: "University of Pennsylvania Perelman School of Medicine" },
      { name: "Esther Cha", role: "Education / Mentorship Chair", school: "Drexel University College of Medicine" },
      { name: "Katherine Park", role: "Education / Mentorship Chair", school: "Philadelphia College of Osteopathic Medicine" },
      { name: "Uvin Ko", role: "Events / Programming Chair", school: "University of Pennsylvania Perelman School of Medicine" },
      { name: "Hyun Kim", role: "Communications / Social Media Chair", school: "University of Pennsylvania Perelman School of Medicine" },
      { name: "William Han", role: "Research Chair", school: "Lewis Katz School of Medicine at Temple University" },
    ],
    contacts: [],
  },
  {
    slug: "dmv",
    name: "DMV",
    short: "DMV",
    lat: 38.9072, lon: -77.0369,
    label: { dx: 210, dy: 30, align: "left" },
    email: "kamsadmv2026@gmail.com",
    instagram: "@kamsa.dmv",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: false,
    schools: [
      { url: "https://smhs.gwu.edu", name: "George Washington University School of Medicine and Health Sciences", city: "Washington, DC" },
      { url: "https://som.georgetown.edu", name: "Georgetown University School of Medicine", city: "Washington, DC" },
      { url: "https://www.hopkinsmedicine.org/som", name: "Johns Hopkins University School of Medicine", city: "Baltimore, MD" },
      { url: "https://www.medschool.umaryland.edu", name: "University of Maryland School of Medicine", city: "Baltimore, MD" },
      { url: "https://www.usuhs.edu", name: "Uniformed Services University of the Health Sciences", city: "Bethesda, MD" },
      { url: "https://med.virginia.edu", name: "University of Virginia School of Medicine", city: "Charlottesville, VA" },
      { url: "https://medschool.vcu.edu", name: "Virginia Commonwealth University School of Medicine", city: "Richmond, VA" },
      { url: "https://www.odu.edu/vahsc", name: "Macon & Joan Brock Virginia Health Sciences at Old Dominion University", city: "Norfolk, VA" },
      { url: "https://medicine.vtc.vt.edu", name: "Virginia Tech Carilion School of Medicine", city: "Roanoke, VA" },
      { url: "https://www.vcom.edu", name: "Edward Via College of Osteopathic Medicine", city: "Blacksburg, VA" },
    ],
    roster: [
      { name: "Bryan Kwon", role: "President", school: "George Washington University School of Medicine and Health Sciences" },
      { name: "Christine Kim", role: "President", school: "Georgetown University School of Medicine" },
      { name: "David Kim", role: "Vice President", school: "George Washington University School of Medicine and Health Sciences" },
      { name: "Stella Lee", role: "Vice President", school: "Georgetown University School of Medicine" },
      { name: "Chelyn Park", role: "Secretary", school: "Georgetown University School of Medicine" },
      { name: "Siyun Lee", role: "Treasurer", school: "Johns Hopkins University School of Medicine" },
      { name: "Edward Park", role: "Treasurer", school: "Georgetown University School of Medicine" },
      { name: "Hannah Lee", role: "Publicity / Communications", school: "George Washington University School of Medicine and Health Sciences" },
      { name: "Yunho Shin", role: "Georgetown Campus Rep", school: "Georgetown University School of Medicine" },
      { name: "Sam Kwon", role: "GWU Campus Rep", school: "George Washington University School of Medicine and Health Sciences" },
    ],
    contacts: [],
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    short: "North Carolina",
    lat: 36.0999, lon: -80.2442,
    label: { dx: 210, dy: 80, align: "left" },
    email: "kamsanorthcarolina@gmail.com",
    instagram: "@kamsa_nc",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://school.wakehealth.edu", name: "Wake Forest University School of Medicine", city: "Winston-Salem, NC" },
      { url: "https://www.med.unc.edu", name: "UNC School of Medicine", city: "Chapel Hill, NC" },
      { url: "https://medschool.duke.edu", name: "Duke University School of Medicine", city: "Durham, NC" },
      { url: "https://brody.ecu.edu", name: "Brody School of Medicine at East Carolina University", city: "Greenville, NC" },
      { url: "https://www.campbell.edu/medicine/", name: "Campbell University Jerry M. Wallace School of Osteopathic Medicine", city: "Lillington, NC" },
    ],
    roster: [],
    contacts: [
      { name: "Nuri Park", role: "Chapter contact", school: "Wake Forest University School of Medicine" },
      { name: "Patrick Cheon", role: "Chapter contact", school: "Wake Forest University School of Medicine" },
    ],
  },
  {
    slug: "georgia",
    name: "Georgia",
    short: "Georgia",
    lat: 33.749, lon: -84.388,
    label: { dx: 0, dy: 52, align: "center" },
    email: "gakamsa@gmail.com",
    instagram: null,
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://med.emory.edu", name: "Emory University School of Medicine", city: "Atlanta, GA" },
      { url: "https://www.augusta.edu/mcg/", name: "Medical College of Georgia at Augusta University", city: "Augusta, GA" },
      { url: "https://medicine.morehouse.edu", name: "Morehouse School of Medicine", city: "Atlanta, GA" },
      { url: "https://www.mercer.edu/medicine/", name: "Mercer University School of Medicine", city: "Macon, GA" },
      { url: "https://pcom.edu/campuses/georgia-campus/", name: "PCOM Georgia", city: "Suwanee, GA" },
    ],
    roster: [],
    contacts: [
      { name: "Hyungyu Lee", role: "Chapter contact", school: "Emory University School of Medicine" },
      { name: "H. Byun", role: "Chapter contact", school: "Medical College of Georgia at Augusta University" },
    ],
  },
  {
    slug: "ohio",
    name: "Ohio",
    short: "Ohio",
    lat: 39.9612, lon: -82.9988,
    label: { dx: -14, dy: 46, align: "right" },
    email: "kamsaohio@gmail.com",
    instagram: "@kamsaohio",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: false,
    schools: [
      { url: "https://medicine.wright.edu", name: "Wright State University Boonshoft School of Medicine", city: "Dayton, OH" },
      { url: "https://www.neomed.edu", name: "Northeast Ohio Medical University", city: "Rootstown, OH" },
      { url: "https://case.edu/medicine/", name: "Case Western Reserve University School of Medicine", city: "Cleveland, OH" },
      { url: "https://my.clevelandclinic.org/departments/education/lerner-college-medicine", name: "Cleveland Clinic Lerner College of Medicine", city: "Cleveland, OH" },
    ],
    roster: [
      { name: "Sumin Byoun", role: "President", school: "Wright State University Boonshoft School of Medicine" },
      { name: "Jonathan Jang", role: "President / Outreach Chair", school: "Northeast Ohio Medical University" },
      { name: "Su Jin Lim", role: "Vice President / Secretary", school: "Northeast Ohio Medical University" },
      { name: "Soobien Lee", role: "Vice President / Social Media Chair", school: "Case Western Reserve University School of Medicine" },
      { name: "Victoria Kim", role: "Treasurer", school: "Cleveland Clinic Lerner College of Medicine" },
    ],
    contacts: [],
  },
  {
    slug: "michigan",
    name: "Michigan",
    short: "Michigan",
    lat: 42.2917, lon: -85.5872,
    label: { dx: 6, dy: -34, align: "left" },
    email: "kamsamichigan@gmail.com",
    instagram: "@kamsamichigan",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://wmed.edu", name: "Western Michigan University Homer Stryker M.D. School of Medicine", city: "Kalamazoo, MI" },
      { url: "https://medicine.umich.edu", name: "University of Michigan Medical School", city: "Ann Arbor, MI" },
      { url: "https://med.wayne.edu", name: "Wayne State University School of Medicine", city: "Detroit, MI" },
      { url: "https://humanmedicine.msu.edu", name: "Michigan State University College of Human Medicine", city: "East Lansing, MI" },
      { url: "https://www.oakland.edu/medicine/", name: "Oakland University William Beaumont School of Medicine", city: "Rochester, MI" },
      { url: "https://www.cmich.edu/colleges/cmed", name: "Central Michigan University College of Medicine", city: "Mount Pleasant, MI" },
    ],
    roster: [],
    contacts: [
      { name: "Shane Kim", role: "Chapter contact", school: "Western Michigan University Homer Stryker M.D. School of Medicine" },
    ],
  },
  {
    slug: "chicago",
    name: "Chicago",
    short: "Chicago",
    lat: 41.8781, lon: -87.6298,
    label: { dx: -14, dy: -6, align: "right" },
    email: "chicagokamsa@gmail.com",
    instagram: "@kamsa.chicago",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: false,
    schools: [
      { url: "https://chicago.medicine.uic.edu", name: "University of Illinois at Chicago College of Medicine", city: "Chicago, IL" },
      { url: "https://www.rushu.rush.edu/rush-medical-college", name: "Rush Medical College", city: "Chicago, IL" },
      { url: "https://pritzker.uchicago.edu", name: "University of Chicago Pritzker School of Medicine", city: "Chicago, IL" },
      { url: "https://www.luc.edu/stritch/", name: "Loyola University Chicago Stritch School of Medicine", city: "Maywood, IL" },
      { url: "https://www.rosalindfranklin.edu", name: "Rosalind Franklin University of Medicine and Science", city: "North Chicago, IL" },
      { url: "https://www.feinberg.northwestern.edu", name: "Northwestern University Feinberg School of Medicine", city: "Chicago, IL" },
      { url: "https://medicine.illinois.edu", name: "Carle Illinois College of Medicine", city: "Urbana, IL" },
      { url: "https://www.midwestern.edu", name: "Midwestern University Chicago College of Osteopathic Medicine", city: "Downers Grove, IL" },
    ],
    roster: [
      { name: "Billy So", role: "President", school: "University of Illinois at Chicago" },
      { name: "Kevin Han", role: "President", school: "Rush Medical College" },
      { name: "Lauren Kang", role: "Vice President", school: "University of Chicago Pritzker School of Medicine" },
      { name: "Catherine Kang", role: "Secretary", school: "Loyola University Chicago Stritch School of Medicine" },
      { name: "Ava Kim", role: "Treasurer / Loyola Representative", school: "Loyola University Chicago Stritch School of Medicine" },
      { name: "Sungki Lee", role: "Community Outreach Chair", school: "Rush Medical College" },
      { name: "Changhun Yang", role: "Communications Chair", school: "University of Illinois at Chicago" },
      { name: "Junyun Park", role: "Social Chair", school: "University of Illinois at Chicago" },
      { name: "Daniel Yoo", role: "UIC Representative", school: "University of Illinois at Chicago" },
      { name: "Andy Kim", role: "UIC Representative", school: "University of Illinois at Chicago" },
      { name: "Jaeson Kim", role: "Rosalind Franklin Representative", school: "Rosalind Franklin University of Medicine and Science" },
      { name: "Isabelle Kang", role: "Northwestern Representative", school: "Northwestern University Feinberg School of Medicine" },
      { name: "Joseph Yoo", role: "Rush Representative", school: "Rush Medical College" },
      { name: "Sangjoon Lee", role: "Carle UIUC Representative", school: "Carle Illinois College of Medicine" },
      { name: "Lydia Jun", role: "Midwestern Representative", school: "Midwestern University Chicago College of Osteopathic Medicine" },
    ],
    contacts: [],
  },
  {
    slug: "texas",
    name: "Texas",
    short: "Texas",
    lat: 29.7604, lon: -95.3698,
    label: { dx: 0, dy: 50, align: "center" },
    email: "kamsatexas@gmail.com",
    instagram: "@kamsatexas",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: true,
    schools: [
      { url: "https://med.uth.edu", name: "McGovern Medical School at UTHealth Houston", city: "Houston, TX" },
      { url: "https://www.bcm.edu", name: "Baylor College of Medicine", city: "Houston, TX" },
      { url: "https://dellmed.utexas.edu", name: "Dell Medical School at UT Austin", city: "Austin, TX" },
      { url: "https://www.utsouthwestern.edu/education/medical-school/", name: "UT Southwestern Medical School", city: "Dallas, TX" },
      { url: "https://lsom.uthscsa.edu", name: "UT Health San Antonio Long School of Medicine", city: "San Antonio, TX" },
      { url: "https://medicine.tamu.edu", name: "Texas A&M University School of Medicine", city: "Bryan, TX" },
      { url: "https://www.ttuhsc.edu/medicine/", name: "Texas Tech University Health Sciences Center School of Medicine", city: "Lubbock, TX" },
    ],
    roster: [],
    contacts: [
      { name: "Sara S. Koh", role: "Chapter contact", school: "McGovern Medical School at UTHealth Houston" },
      { name: "Nia Choi", role: "Chapter contact", school: "Baylor College of Medicine" },
    ],
  },
  {
    slug: "southern-california",
    name: "Southern California",
    short: "SoCal",
    lat: 34.0522, lon: -118.2437,
    label: { dx: -14, dy: 34, align: "right" },
    email: "kamsa.crc@gmail.com",
    instagram: "@kamsa.crc",
    discord: "https://discord.gg/EyeU2wSkG",
    schoolsPartial: false,
    schools: [
      { url: "https://medschool.ucla.edu", name: "UCLA David Geffen School of Medicine", city: "Los Angeles, CA" },
      { url: "https://medschool.ucsd.edu", name: "UC San Diego School of Medicine", city: "La Jolla, CA" },
      { url: "https://som.uci.edu", name: "UC Irvine School of Medicine", city: "Irvine, CA" },
      { url: "https://medschool.ucr.edu", name: "UC Riverside School of Medicine", city: "Riverside, CA" },
      { url: "https://keck.usc.edu/education/keck-school-of-medicine/", name: "Keck School of Medicine of USC", city: "Los Angeles, CA" },
      { url: "https://medschool.kp.org", name: "Kaiser Permanente Bernard J. Tyson School of Medicine", city: "Pasadena, CA" },
      { url: "https://medicine.llu.edu", name: "Loma Linda University School of Medicine", city: "Loma Linda, CA" },
      { url: "https://cusm.org", name: "California University of Science and Medicine", city: "Colton, CA" },
      { url: "https://www.westernu.edu/osteopathic/", name: "Western University of Health Sciences COMP", city: "Pomona, CA" },
    ],
    roster: [
      { name: "Justin Park", role: "President", school: "UCLA David Geffen School of Medicine" },
      { name: "Heidi Kim", role: "President", school: "UCLA David Geffen School of Medicine" },
      { name: "Yedam Hong", role: "President", school: "UC Irvine School of Medicine" },
      { name: "Harry Park", role: "Vice President", school: "Keck School of Medicine of USC" },
      { name: "Christine Lee", role: "Vice President", school: "UC Irvine School of Medicine" },
      { name: "Justin Yoon", role: "Secretary", school: "California University of Science and Medicine" },
      { name: "Justin Shon", role: "Treasurer", school: "Western University of Health Sciences" },
      { name: "Shine Lim", role: "Membership Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Jiwon Suh", role: "Membership Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Gahee Kim", role: "Membership Chair", school: "Western University of Health Sciences" },
      { name: "Diane Park", role: "Membership Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Sion Yoo", role: "Advocacy Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Justin Kim", role: "Advocacy Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Minhyuk Lee", role: "Advocacy Chair", school: "Western University of Health Sciences COMP" },
      { name: "Green Hahm", role: "Advocacy Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Younggyun Kim", role: "Outreach Chair", school: "Keck School of Medicine of USC" },
      { name: "Yoori Cho", role: "Outreach Chair", school: "California University of Science and Medicine" },
      { name: "Susanna Kim", role: "Outreach Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Nathan Kim", role: "Outreach Chair", school: "Keck School of Medicine of USC" },
      { name: "Semi Yoon", role: "Publicity Chair", school: "UCLA David Geffen School of Medicine" },
      { name: "Gloria Oh", role: "Publicity Chair", school: "Loma Linda University School of Medicine" },
    ],
    contacts: [],
  },
];

export const FORMING = [
  { name: "Alabama", email: null, instagram: "@kamsa_alabama" },
  { name: "Florida", email: "flkamsa@gmail.com", instagram: null },
  { name: "Hawaii", email: null, instagram: "@kamsa_hawaii" },
  { name: "Uniformed Services", email: "kamsa.usnc@gmail.com", instagram: "@kamsa.usnc" },
];

export const PARTNERS = [
  { abbr: "APAMSA", name: "Asian Pacific American Medical Student Association", url: "https://www.apamsa.org", blurb: "National partner on advocacy, community health, and Asian American health equity programming." },
  { abbr: "Liner", name: "Liner", url: "https://getliner.com", blurb: "Supports KAMSA members' coursework and research with AI-assisted literature search and study tools." },
  { abbr: "NMDP", name: "National Marrow Donor Program", url: "https://www.nmdp.org", blurb: "Partner on donor registry drives and outreach in Korean American communities." },
  { abbr: "KAMA", name: "Korean American Medical Association", url: "https://www.kamausa.org", blurb: "Physician association providing mentorship, career guidance, and community for students." },
  { abbr: "NATMA", name: "North American Taiwanese Medical Association", url: "https://www.natma.org", blurb: "Sister organization collaborating on cross-community programming and advocacy." },
];

export const bySlug = (slug) => CHAPTERS.find((c) => c.slug === slug);
