// KAMSA regional chapter data. Source: KAMSA Regional Leadership workbook.
// `roster` = confirmed leadership rows. `contacts` = chapter contacts on file where no roster
// has been submitted yet. `schools` marked partial: derived from contact institutions.

export const NATIONAL = {
  email: "kamsa.usa@gmail.com",
  instagram: "https://www.instagram.com/kamsa.usa/",
  instagramHandle: "@kamsa.usa",
  discord: "mailto:kamsa.usa@gmail.com?subject=Discord%20invite%20request",
  form: "https://forms.gle/wnx6NDXZj9i2xNzL9",
};

export const CHAPTERS = [
  {
    slug: "ny-nj",
    name: "New York / New Jersey",
    short: "NY/NJ",
    region: "Mid-Atlantic",
    lat: 40.7128, lon: -74.006,
    label: { dx: 210, dy: -70, align: "left" },
    email: "kamsanynj@gmail.com",
    instagram: "@kamsanynj",
    schoolsPartial: true,
    schools: [
      { url: "https://icahn.mssm.edu", name: "Icahn School of Medicine at Mount Sinai", city: "New York, NY" },
      { url: "https://www.hmsom.org", name: "Hackensack Meridian School of Medicine", city: "Nutley, NJ" },
    ],
    roster: [],
    contacts: [
      { name: "Minwoo Kwon", role: "Chapter contact", school: "Icahn School of Medicine at Mount Sinai", email: "minwoo.kwon@icahn.mssm.edu" },
      { name: "Sohee Kim", role: "Chapter contact", school: "Hackensack Meridian Health", email: "sohee.kim@hmhn.org" },
    ],
  },
  {
    slug: "new-england",
    name: "New England",
    short: "New England",
    region: "Northeast",
    lat: 42.3601, lon: -71.0589,
    label: { dx: 210, dy: -120, align: "left" },
    email: "kamsanewengland@gmail.com",
    instagram: "@kamsa.ne",
    schoolsPartial: true,
    schools: [{ url: "https://www.umassmed.edu", name: "UMass Chan Medical School", city: "Worcester, MA" }],
    roster: [],
    contacts: [
      { name: "SoJung Park", role: "Chapter contact", school: "UMass Chan Medical School", email: "SoJung.Park@umassmed.edu" },
    ],
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    short: "Pennsylvania",
    region: "Mid-Atlantic",
    lat: 39.9526, lon: -75.1652,
    label: { dx: 210, dy: -20, align: "left" },
    email: "kamsa.penn@gmail.com",
    instagram: "@kamsa_penn",
    schoolsPartial: true,
    schools: [
      { url: "https://www.med.upenn.edu", name: "Perelman School of Medicine at the University of Pennsylvania", city: "Philadelphia, PA" },
      { url: "https://www.pcom.edu", name: "Philadelphia College of Osteopathic Medicine", city: "Philadelphia, PA" },
    ],
    roster: [],
    contacts: [
      { name: "Minjae Kim", role: "Chapter contact", school: "Perelman School of Medicine, University of Pennsylvania", email: "minjae.kim@pennmedicine.upenn.edu" },
      { name: "J. Park", role: "Chapter contact", school: "Philadelphia College of Osteopathic Medicine", email: "jp3508@pcom.edu" },
    ],
  },
  {
    slug: "dmv",
    name: "DMV",
    short: "DMV",
    region: "DC / Maryland / Virginia",
    lat: 38.9072, lon: -77.0369,
    label: { dx: 210, dy: 30, align: "left" },
    email: "kamsadmv2026@gmail.com",
    instagram: "@kamsa.dmv",
    schoolsPartial: true,
    schools: [
      { url: "https://som.georgetown.edu", name: "Georgetown University School of Medicine", city: "Washington, DC" },
      { url: "https://smhs.gwu.edu", name: "George Washington University School of Medicine", city: "Washington, DC" },
    ],
    roster: [],
    contacts: [
      { name: "C. Kim", role: "Chapter contact", school: "Georgetown University School of Medicine", email: "cyk15@georgetown.edu" },
      { name: "Bryan Kwon", role: "Chapter contact", school: "George Washington University School of Medicine", email: "bryan.kwon@gwu.edu" },
    ],
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    short: "North Carolina",
    region: "Southeast",
    lat: 36.0999, lon: -80.2442,
    label: { dx: 210, dy: 80, align: "left" },
    email: "kamsanorthcarolina@gmail.com",
    instagram: "@kamsa_nc",
    schoolsPartial: true,
    schools: [{ url: "https://school.wakehealth.edu", name: "Wake Forest University School of Medicine", city: "Winston-Salem, NC" }],
    roster: [],
    contacts: [
      { name: "Nuri Park", role: "Chapter contact", school: "Wake Forest University School of Medicine", email: "nuri.park@wfusm.edu" },
      { name: "Patrick Cheon", role: "Chapter contact", school: "Wake Forest University School of Medicine", email: "patrick.cheon@wfusm.edu" },
    ],
  },
  {
    slug: "georgia",
    name: "Georgia",
    short: "Georgia",
    region: "Southeast",
    lat: 33.749, lon: -84.388,
    label: { dx: 0, dy: 52, align: "center" },
    email: "gakamsa@gmail.com",
    instagram: null,
    schoolsPartial: true,
    schools: [
      { url: "https://med.emory.edu", name: "Emory University School of Medicine", city: "Atlanta, GA" },
      { url: "https://www.augusta.edu/mcg/", name: "Medical College of Georgia at Augusta University", city: "Augusta, GA" },
    ],
    roster: [],
    contacts: [
      { name: "Hyungyu Lee", role: "Chapter contact", school: "Emory University School of Medicine", email: "hyungyu.lee@emory.edu" },
      { name: "H. Byun", role: "Chapter contact", school: "Medical College of Georgia at Augusta University", email: "hbyun@augusta.edu" },
    ],
  },
  {
    slug: "ohio",
    name: "Ohio",
    short: "Ohio",
    region: "Midwest",
    lat: 39.9612, lon: -82.9988,
    label: { dx: -14, dy: 46, align: "right" },
    email: "kamsaohio@gmail.com",
    instagram: "@kamsaohio",
    schoolsPartial: true,
    schools: [{ url: "https://medicine.wright.edu", name: "Wright State University Boonshoft School of Medicine", city: "Dayton, OH" }],
    roster: [],
    contacts: [
      { name: "B. Youn", role: "Chapter contact", school: "Wright State University Boonshoft School of Medicine", email: "byoun.2@wright.edu" },
    ],
  },
  {
    slug: "michigan",
    name: "Michigan",
    short: "Michigan",
    region: "Midwest",
    lat: 42.2917, lon: -85.5872,
    label: { dx: 6, dy: -34, align: "left" },
    email: "kamsamichigan@gmail.com",
    instagram: "@kamsamichigan",
    schoolsPartial: true,
    schools: [{ url: "https://wmed.edu", name: "Western Michigan University Homer Stryker M.D. School of Medicine", city: "Kalamazoo, MI" }],
    roster: [],
    contacts: [
      { name: "Shane Kim", role: "Chapter contact", school: "Western Michigan Homer Stryker M.D. School of Medicine", email: "shane.kim@wmed.edu" },
    ],
  },
  {
    slug: "chicago",
    name: "Chicago",
    short: "Chicago",
    region: "Midwest",
    lat: 41.8781, lon: -87.6298,
    label: { dx: -14, dy: -6, align: "right" },
    email: "chicagokamsa@gmail.com",
    instagram: "@kamsa.chicago",
    schoolsPartial: false,
    schools: [
      { url: "https://chicago.medicine.uic.edu", name: "University of Illinois at Chicago College of Medicine", city: "Chicago, IL" },
      { url: "https://www.rushu.rush.edu/rush-medical-college", name: "Rush Medical College", city: "Chicago, IL" },
      { url: "https://pritzker.uchicago.edu", name: "University of Chicago Pritzker School of Medicine", city: "Chicago, IL" },
      { url: "https://www.luc.edu/stritch/", name: "Loyola University Chicago Stritch School of Medicine", city: "Maywood, IL" },
      { url: "https://www.feinberg.northwestern.edu", name: "Northwestern University Feinberg School of Medicine", city: "Chicago, IL" },
      { url: "https://www.rosalindfranklin.edu", name: "Rosalind Franklin University of Medicine and Science", city: "North Chicago, IL" },
      { url: "https://medicine.illinois.edu", name: "Carle Illinois College of Medicine", city: "Urbana, IL" },
      { url: "https://www.midwestern.edu", name: "Midwestern University Chicago College of Osteopathic Medicine", city: "Downers Grove, IL" },
    ],
    roster: [
      { name: "Billy So", role: "President", school: "University of Illinois at Chicago", email: "bso1@uic.edu" },
      { name: "Kevin Han", role: "President", school: "Rush Medical College", email: "kevin_han@rush.edu" },
      { name: "Lauren Kang", role: "Vice President", school: "University of Chicago Pritzker School of Medicine", email: "lskang@uchicagomedicine.org" },
      { name: "Catherine Kang", role: "Secretary", school: "Loyola University Chicago Stritch School of Medicine", email: "ckang@luc.edu" },
      { name: "Ava Kim", role: "Treasurer / Loyola Representative", school: "Loyola University Chicago Stritch School of Medicine", email: "akim39@luc.edu" },
      { name: "Sungki Lee", role: "Community Outreach Chair", school: "Rush Medical College", email: "Sung-Ki_Lee@rush.edu" },
      { name: "Changhun Yang", role: "Communications Chair", school: "University of Illinois at Chicago", email: "cy19@uic.edu" },
      { name: "Junyun Park", role: "Social Chair", school: "University of Illinois at Chicago", email: "junyunp2@uic.edu" },
      { name: "Daniel Yoo", role: "UIC Representative", school: "University of Illinois at Chicago", email: "gyoo7@uic.edu" },
      { name: "Andy Kim", role: "UIC Representative", school: "University of Illinois at Chicago", email: "akim260@uic.edu" },
      { name: "Jaeson Kim", role: "Rosalind Franklin Representative", school: "Rosalind Franklin University of Medicine and Science", email: "jaeson.kim@my.rfums.org" },
      { name: "Isabelle Kang", role: "Northwestern Representative", school: "Northwestern University Feinberg School of Medicine", email: "isabelle.kang@northwestern.edu" },
      { name: "Joseph Yoo", role: "Rush Representative", school: "Rush Medical College", email: "Joseph_s_yoo@rush.edu" },
      { name: "Sangjoon Lee", role: "Carle UIUC Representative", school: "Carle Illinois College of Medicine", email: "sl257@illinois.edu" },
      { name: "Lydia Jun", role: "Midwestern Representative", school: "Midwestern University Chicago College of Osteopathic Medicine", email: "lydia.jun@midwestern.edu" },
    ],
    contacts: [],
  },
  {
    slug: "texas",
    name: "Texas",
    short: "Texas",
    region: "South",
    lat: 29.7604, lon: -95.3698,
    label: { dx: 0, dy: 50, align: "center" },
    email: "kamsatexas@gmail.com",
    instagram: "@kamsatexas",
    schoolsPartial: true,
    schools: [
      { url: "https://med.uth.edu", name: "McGovern Medical School at UTHealth Houston", city: "Houston, TX" },
      { url: "https://www.bcm.edu", name: "Baylor College of Medicine", city: "Houston, TX" },
    ],
    roster: [],
    contacts: [
      { name: "Sara S. Koh", role: "Chapter contact", school: "McGovern Medical School at UTHealth Houston", email: "sara.s.koh@uth.tmc.edu" },
      { name: "Nia Choi", role: "Chapter contact", school: "Baylor College of Medicine", email: "nia.choi@bcm.edu" },
    ],
  },
  {
    slug: "southern-california",
    name: "Southern California",
    short: "SoCal",
    region: "West",
    lat: 34.0522, lon: -118.2437,
    label: { dx: -14, dy: 34, align: "right" },
    email: "kamsa.crc@gmail.com",
    instagram: "@kamsa.crc",
    schoolsPartial: true,
    schools: [{ url: "https://medschool.ucla.edu", name: "David Geffen School of Medicine at UCLA", city: "Los Angeles, CA" }],
    roster: [],
    contacts: [
      { name: "Nathan Kim", role: "Chapter contact", school: "—", email: "dnathankim@gmail.com" },
      { name: "S. Kim", role: "Chapter contact", school: "David Geffen School of Medicine at UCLA", email: "songhkim@g.ucla.edu" },
    ],
  },
];

export const FORMING = [
  { name: "Alabama", email: null, instagram: null, contacts: ["kyublaze@uab.edu", "cbig@uab.edu", "hyolim@uab.edu"] },
  { name: "Florida", email: "flkamsa@gmail.com", instagram: null, contacts: [] },
  { name: "Hawaii", email: null, instagram: null, contacts: [] },
  { name: "Uniformed Services", email: "kamsa.usnc@gmail.com", instagram: "@kamsa.usnc", contacts: [] },
];

export const bySlug = (slug) => CHAPTERS.find((c) => c.slug === slug);
